name: Build Arriba dotnetcore

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      SOLUTION: ./src/Arriba/Arriba.Core.sln
      OUTPUT_DIR: ./output/bin
      CONFIGURATION: Release
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Build Arriba Solution
        run: dotnet build $SOLUTION --configuration $CONFIGURATION --output $OUTPUT_DIR
      - name: Test Arriba Solution
        run: dotnet test $SOLUTION --configuration $CONFIGURATION --logger:trx
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Arriba
          path: $OUTPUT_DIR
